// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS-4-6gCayUkeAuh7VzWrZr0mAhnsOEAI',
    appId: '1:1002898419393:web:cbe3303a97c6c5fb27ee40',
    messagingSenderId: '1002898419393',
    projectId: 'my-apart-40f06',
    authDomain: 'my-apart-40f06.firebaseapp.com',
    storageBucket: 'my-apart-40f06.firebasestorage.app',
    measurementId: 'G-45DJTFKF6C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRJiM2LTcY6uQyBRycK0BXZCGvVmatlDE',
    appId: '1:1002898419393:android:11147e3a7070cbab27ee40',
    messagingSenderId: '1002898419393',
    projectId: 'my-apart-40f06',
    storageBucket: 'my-apart-40f06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFtcokdmulQg5pLXYO6_bWzLxAZReEN1s',
    appId: '1:1002898419393:ios:4b06e81d6acf5c6b27ee40',
    messagingSenderId: '1002898419393',
    projectId: 'my-apart-40f06',
    storageBucket: 'my-apart-40f06.firebasestorage.app',
    iosBundleId: 'com.example.myApart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFtcokdmulQg5pLXYO6_bWzLxAZReEN1s',
    appId: '1:1002898419393:ios:4b06e81d6acf5c6b27ee40',
    messagingSenderId: '1002898419393',
    projectId: 'my-apart-40f06',
    storageBucket: 'my-apart-40f06.firebasestorage.app',
    iosBundleId: 'com.example.myApart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS-4-6gCayUkeAuh7VzWrZr0mAhnsOEAI',
    appId: '1:1002898419393:web:eea85989f3e7d4f627ee40',
    messagingSenderId: '1002898419393',
    projectId: 'my-apart-40f06',
    authDomain: 'my-apart-40f06.firebaseapp.com',
    storageBucket: 'my-apart-40f06.firebasestorage.app',
    measurementId: 'G-WTZQ8T1S4V',
  );
}
